/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.implementation;

import com.azure.marketplace.Fulfillments;
import com.azure.marketplace.MarketplaceClient;
import com.azure.marketplace.Meterings;
import com.azure.marketplace.SubscriptionOperations;
import com.microsoft.azure.AzureClient;
import com.microsoft.azure.AzureServiceClient;
import com.microsoft.rest.credentials.ServiceClientCredentials;
import com.microsoft.rest.RestClient;

/**
 * Initializes a new instance of the MarketplaceClientImpl class.
 */
public class MarketplaceClientImpl extends AzureServiceClient implements MarketplaceClient {
    /** the {@link AzureClient} used for long running operations. */
    private AzureClient azureClient;

    /**
     * Gets the {@link AzureClient} used for long running operations.
     * @return the azure client;
     */
    public AzureClient getAzureClient() {
        return this.azureClient;
    }

    /** The preferred language for the response. */
    private String acceptLanguage;

    /**
     * Gets The preferred language for the response.
     *
     * @return the acceptLanguage value.
     */
    public String acceptLanguage() {
        return this.acceptLanguage;
    }

    /**
     * Sets The preferred language for the response.
     *
     * @param acceptLanguage the acceptLanguage value.
     * @return the service client itself
     */
    public MarketplaceClientImpl withAcceptLanguage(String acceptLanguage) {
        this.acceptLanguage = acceptLanguage;
        return this;
    }

    /** The retry timeout in seconds for Long Running Operations. Default value is 30. */
    private int longRunningOperationRetryTimeout;

    /**
     * Gets The retry timeout in seconds for Long Running Operations. Default value is 30.
     *
     * @return the longRunningOperationRetryTimeout value.
     */
    public int longRunningOperationRetryTimeout() {
        return this.longRunningOperationRetryTimeout;
    }

    /**
     * Sets The retry timeout in seconds for Long Running Operations. Default value is 30.
     *
     * @param longRunningOperationRetryTimeout the longRunningOperationRetryTimeout value.
     * @return the service client itself
     */
    public MarketplaceClientImpl withLongRunningOperationRetryTimeout(int longRunningOperationRetryTimeout) {
        this.longRunningOperationRetryTimeout = longRunningOperationRetryTimeout;
        return this;
    }

    /** Whether a unique x-ms-client-request-id should be generated. When set to true a unique x-ms-client-request-id value is generated and included in each request. Default is true. */
    private boolean generateClientRequestId;

    /**
     * Gets Whether a unique x-ms-client-request-id should be generated. When set to true a unique x-ms-client-request-id value is generated and included in each request. Default is true.
     *
     * @return the generateClientRequestId value.
     */
    public boolean generateClientRequestId() {
        return this.generateClientRequestId;
    }

    /**
     * Sets Whether a unique x-ms-client-request-id should be generated. When set to true a unique x-ms-client-request-id value is generated and included in each request. Default is true.
     *
     * @param generateClientRequestId the generateClientRequestId value.
     * @return the service client itself
     */
    public MarketplaceClientImpl withGenerateClientRequestId(boolean generateClientRequestId) {
        this.generateClientRequestId = generateClientRequestId;
        return this;
    }

    /**
     * The Fulfillments object to access its operations.
     */
    private Fulfillments fulfillments;

    /**
     * Gets the Fulfillments object to access its operations.
     * @return the Fulfillments object.
     */
    public Fulfillments fulfillments() {
        return this.fulfillments;
    }

    /**
     * The SubscriptionOperations object to access its operations.
     */
    private SubscriptionOperations subscriptionOperations;

    /**
     * Gets the SubscriptionOperations object to access its operations.
     * @return the SubscriptionOperations object.
     */
    public SubscriptionOperations subscriptionOperations() {
        return this.subscriptionOperations;
    }

    /**
     * The Meterings object to access its operations.
     */
    private Meterings meterings;

    /**
     * Gets the Meterings object to access its operations.
     * @return the Meterings object.
     */
    public Meterings meterings() {
        return this.meterings;
    }

    /**
     * Initializes an instance of MarketplaceClient client.
     *
     * @param credentials the management credentials for Azure
     */
    public MarketplaceClientImpl(ServiceClientCredentials credentials) {
        this("https://marketplaceapi.microsoft.com/api", credentials);
    }

    /**
     * Initializes an instance of MarketplaceClient client.
     *
     * @param baseUrl the base URL of the host
     * @param credentials the management credentials for Azure
     */
    public MarketplaceClientImpl(String baseUrl, ServiceClientCredentials credentials) {
        super(baseUrl, credentials);
        initialize();
    }

    /**
     * Initializes an instance of MarketplaceClient client.
     *
     * @param restClient the REST client to connect to Azure.
     */
    public MarketplaceClientImpl(RestClient restClient) {
        super(restClient);
        initialize();
    }

    protected void initialize() {
        this.acceptLanguage = "en-US";
        this.longRunningOperationRetryTimeout = 30;
        this.generateClientRequestId = true;
        this.fulfillments = new FulfillmentsImpl(restClient().retrofit(), this);
        this.subscriptionOperations = new SubscriptionOperationsImpl(restClient().retrofit(), this);
        this.meterings = new MeteringsImpl(restClient().retrofit(), this);
        this.azureClient = new AzureClient(this);
    }

    /**
     * Gets the User-Agent header for the client.
     *
     * @return the user agent string.
     */
    @Override
    public String userAgent() {
        return String.format("%s (%s, %s)", super.userAgent(), "MarketplaceClient", "2018-08-31");
    }
}
