// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.saas.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.UUID;

/** The AadIdentifier model. */
@Fluent
public final class AadIdentifier {
    /*
     * The emailId property.
     */
    @JsonProperty(value = "emailId")
    private String emailId;

    /*
     * The objectId property.
     */
    @JsonProperty(value = "objectId")
    private UUID objectId;

    /*
     * The tenantId property.
     */
    @JsonProperty(value = "tenantId")
    private UUID tenantId;

    /*
     * The puid property.
     */
    @JsonProperty(value = "puid")
    private String puid;

    /**
     * Get the emailId property: The emailId property.
     *
     * @return the emailId value.
     */
    public String getEmailId() {
        return this.emailId;
    }

    /**
     * Set the emailId property: The emailId property.
     *
     * @param emailId the emailId value to set.
     * @return the AadIdentifier object itself.
     */
    public AadIdentifier setEmailId(String emailId) {
        this.emailId = emailId;
        return this;
    }

    /**
     * Get the objectId property: The objectId property.
     *
     * @return the objectId value.
     */
    public UUID getObjectId() {
        return this.objectId;
    }

    /**
     * Set the objectId property: The objectId property.
     *
     * @param objectId the objectId value to set.
     * @return the AadIdentifier object itself.
     */
    public AadIdentifier setObjectId(UUID objectId) {
        this.objectId = objectId;
        return this;
    }

    /**
     * Get the tenantId property: The tenantId property.
     *
     * @return the tenantId value.
     */
    public UUID getTenantId() {
        return this.tenantId;
    }

    /**
     * Set the tenantId property: The tenantId property.
     *
     * @param tenantId the tenantId value to set.
     * @return the AadIdentifier object itself.
     */
    public AadIdentifier setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    /**
     * Get the puid property: The puid property.
     *
     * @return the puid value.
     */
    public String getPuid() {
        return this.puid;
    }

    /**
     * Set the puid property: The puid property.
     *
     * @param puid the puid value to set.
     * @return the AadIdentifier object itself.
     */
    public AadIdentifier setPuid(String puid) {
        this.puid = puid;
        return this;
    }
}
