// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.saas.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The FulfillmentInternalServerErrorResponse model. */
@Fluent
public final class FulfillmentInternalServerErrorResponse {
    /*
     * The error property.
     */
    @JsonProperty(value = "error")
    private FulfillmentInternalServerErrorResponseError error;

    /**
     * Get the error property: The error property.
     *
     * @return the error value.
     */
    public FulfillmentInternalServerErrorResponseError getError() {
        return this.error;
    }

    /**
     * Set the error property: The error property.
     *
     * @param error the error value to set.
     * @return the FulfillmentInternalServerErrorResponse object itself.
     */
    public FulfillmentInternalServerErrorResponse setError(FulfillmentInternalServerErrorResponseError error) {
        this.error = error;
        return this;
    }
}
