// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.saas.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The MeteringDimension model. */
@Fluent
public final class MeteringDimension {
    /*
     * The id property.
     */
    @JsonProperty(value = "id")
    private String id;

    /*
     * The currency property.
     */
    @JsonProperty(value = "currency")
    private String currency;

    /*
     * The pricePerUnit property.
     */
    @JsonProperty(value = "pricePerUnit")
    private Float pricePerUnit;

    /*
     * The unitOfMeasure property.
     */
    @JsonProperty(value = "unitOfMeasure")
    private String unitOfMeasure;

    /*
     * The displayName property.
     */
    @JsonProperty(value = "displayName")
    private String displayName;

    /**
     * Get the id property: The id property.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Set the id property: The id property.
     *
     * @param id the id value to set.
     * @return the MeteringDimension object itself.
     */
    public MeteringDimension setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the currency property: The currency property.
     *
     * @return the currency value.
     */
    public String getCurrency() {
        return this.currency;
    }

    /**
     * Set the currency property: The currency property.
     *
     * @param currency the currency value to set.
     * @return the MeteringDimension object itself.
     */
    public MeteringDimension setCurrency(String currency) {
        this.currency = currency;
        return this;
    }

    /**
     * Get the pricePerUnit property: The pricePerUnit property.
     *
     * @return the pricePerUnit value.
     */
    public Float getPricePerUnit() {
        return this.pricePerUnit;
    }

    /**
     * Set the pricePerUnit property: The pricePerUnit property.
     *
     * @param pricePerUnit the pricePerUnit value to set.
     * @return the MeteringDimension object itself.
     */
    public MeteringDimension setPricePerUnit(Float pricePerUnit) {
        this.pricePerUnit = pricePerUnit;
        return this;
    }

    /**
     * Get the unitOfMeasure property: The unitOfMeasure property.
     *
     * @return the unitOfMeasure value.
     */
    public String getUnitOfMeasure() {
        return this.unitOfMeasure;
    }

    /**
     * Set the unitOfMeasure property: The unitOfMeasure property.
     *
     * @param unitOfMeasure the unitOfMeasure value to set.
     * @return the MeteringDimension object itself.
     */
    public MeteringDimension setUnitOfMeasure(String unitOfMeasure) {
        this.unitOfMeasure = unitOfMeasure;
        return this;
    }

    /**
     * Get the displayName property: The displayName property.
     *
     * @return the displayName value.
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Set the displayName property: The displayName property.
     *
     * @param displayName the displayName value to set.
     * @return the MeteringDimension object itself.
     */
    public MeteringDimension setDisplayName(String displayName) {
        this.displayName = displayName;
        return this;
    }
}
