// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.saas.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The MeteringedQuantityIncluded model. */
@Fluent
public final class MeteringedQuantityIncluded {
    /*
     * The dimensionId property.
     */
    @JsonProperty(value = "dimensionId")
    private String dimensionId;

    /*
     * The units property.
     */
    @JsonProperty(value = "units")
    private String units;

    /**
     * Get the dimensionId property: The dimensionId property.
     *
     * @return the dimensionId value.
     */
    public String getDimensionId() {
        return this.dimensionId;
    }

    /**
     * Set the dimensionId property: The dimensionId property.
     *
     * @param dimensionId the dimensionId value to set.
     * @return the MeteringedQuantityIncluded object itself.
     */
    public MeteringedQuantityIncluded setDimensionId(String dimensionId) {
        this.dimensionId = dimensionId;
        return this;
    }

    /**
     * Get the units property: The units property.
     *
     * @return the units value.
     */
    public String getUnits() {
        return this.units;
    }

    /**
     * Set the units property: The units property.
     *
     * @param units the units value to set.
     * @return the MeteringedQuantityIncluded object itself.
     */
    public MeteringedQuantityIncluded setUnits(String units) {
        this.units = units;
        return this;
    }
}
