// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.saas.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Defines values for OperationActionEnum. */
public enum OperationActionEnum {
    /** Enum value Unsubscribe. */
    UNSUBSCRIBE("Unsubscribe"),

    /** Enum value ChangePlan. */
    CHANGE_PLAN("ChangePlan"),

    /** Enum value ChangeQuantity. */
    CHANGE_QUANTITY("ChangeQuantity"),

    /** Enum value Suspend. */
    SUSPEND("Suspend"),

    /** Enum value Reinstate. */
    REINSTATE("Reinstate"),
    
    /** Enum value Renew. */
    RENEW("Renew");

    /** The actual serialized value for a OperationActionEnum instance. */
    private final String value;

    OperationActionEnum(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a OperationActionEnum instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed OperationActionEnum object, or null if unable to parse.
     */
    @JsonCreator
    public static OperationActionEnum fromString(String value) {
        OperationActionEnum[] items = OperationActionEnum.values();
        for (OperationActionEnum item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
