// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.saas.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The OperationList model. */
@Fluent
public final class OperationList {
    /*
     * The operations property.
     */
    @JsonProperty(value = "operations")
    private List<Operation> operations;

    /**
     * Get the operations property: The operations property.
     *
     * @return the operations value.
     */
    public List<Operation> getOperations() {
        return this.operations;
    }

    /**
     * Set the operations property: The operations property.
     *
     * @param operations the operations value to set.
     * @return the OperationList object itself.
     */
    public OperationList setOperations(List<Operation> operations) {
        this.operations = operations;
        return this;
    }
}
