// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.saas.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Defines values for SubscriptionStatusEnum. */
public enum SubscriptionStatusEnum {
    /** Enum value NotStarted. */
    NOT_STARTED("NotStarted"),

    /** Enum value PendingFulfillmentStart. */
    PENDING_FULFILLMENT_START("PendingFulfillmentStart"),

    /** Enum value Subscribed. */
    SUBSCRIBED("Subscribed"),

    /** Enum value Suspended. */
    SUSPENDED("Suspended"),

    /** Enum value Unsubscribed. */
    UNSUBSCRIBED("Unsubscribed");

    /** The actual serialized value for a SubscriptionStatusEnum instance. */
    private final String value;

    SubscriptionStatusEnum(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a SubscriptionStatusEnum instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed SubscriptionStatusEnum object, or null if unable to parse.
     */
    @JsonCreator
    public static SubscriptionStatusEnum fromString(String value) {
        SubscriptionStatusEnum[] items = SubscriptionStatusEnum.values();
        for (SubscriptionStatusEnum item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
