// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.saas.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** The SubscriptionTerm model. */
@Fluent
public final class SubscriptionTerm {
    /*
     * The startDate property.
     */
    @JsonProperty(value = "startDate")
    private OffsetDateTime startDate;

    /*
     * The endDate property.
     */
    @JsonProperty(value = "endDate")
    private OffsetDateTime endDate;

    /**
     * Get the startDate property: The startDate property.
     *
     * @return the startDate value.
     */
    public OffsetDateTime getStartDate() {
        return this.startDate;
    }

    /**
     * Set the startDate property: The startDate property.
     *
     * @param startDate the startDate value to set.
     * @return the SubscriptionTerm object itself.
     */
    public SubscriptionTerm setStartDate(OffsetDateTime startDate) {
        this.startDate = startDate;
        return this;
    }

    /**
     * Get the endDate property: The endDate property.
     *
     * @return the endDate value.
     */
    public OffsetDateTime getEndDate() {
        return this.endDate;
    }

    /**
     * Set the endDate property: The endDate property.
     *
     * @param endDate the endDate value to set.
     * @return the SubscriptionTerm object itself.
     */
    public SubscriptionTerm setEndDate(OffsetDateTime endDate) {
        this.endDate = endDate;
        return this;
    }
}
