// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.saas.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The SubscriptionsResponse model. */
@Fluent
public final class SubscriptionsResponse {
    /*
     * The subscriptions property.
     */
    @JsonProperty(value = "subscriptions")
    private List<Subscription> subscriptions;

    /*
     * Link to get the next set of subscriptions.
     */
    @JsonProperty(value = "@nextLink")
    private String nextLink;

    /**
     * Get the subscriptions property: The subscriptions property.
     *
     * @return the subscriptions value.
     */
    public List<Subscription> getSubscriptions() {
        return this.subscriptions;
    }

    /**
     * Set the subscriptions property: The subscriptions property.
     *
     * @param subscriptions the subscriptions value to set.
     * @return the SubscriptionsResponse object itself.
     */
    public SubscriptionsResponse setSubscriptions(List<Subscription> subscriptions) {
        this.subscriptions = subscriptions;
        return this;
    }

    /**
     * Get the nextLink property: Link to get the next set of subscriptions.
     *
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: Link to get the next set of subscriptions.
     *
     * @param nextLink the nextLink value to set.
     * @return the SubscriptionsResponse object itself.
     */
    public SubscriptionsResponse setNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }
}
