// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.saas.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Defines values for TermUnitEnum. */
public enum TermUnitEnum {
    /** Enum value P1M. */
    P1M("P1M"),

    /** Enum value P1Y. */
    P1Y("P1Y");

    /** The actual serialized value for a TermUnitEnum instance. */
    private final String value;

    TermUnitEnum(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a TermUnitEnum instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed TermUnitEnum object, or null if unable to parse.
     */
    @JsonCreator
    public static TermUnitEnum fromString(String value) {
        TermUnitEnum[] items = TermUnitEnum.values();
        for (TermUnitEnum item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
