/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Summary of the subscription.
 */
public class ResolvedSubscription {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private UUID id;

    /**
     * The subscriptionName property.
     */
    @JsonProperty(value = "subscriptionName")
    private String subscriptionName;

    /**
     * The offerId property.
     */
    @JsonProperty(value = "offerId")
    private String offerId;

    /**
     * The planId property.
     */
    @JsonProperty(value = "planId")
    private String planId;

    /**
     * The quantity property.
     */
    @JsonProperty(value = "quantity")
    private Long quantity;

    /**
     * The subscription property.
     */
    @JsonProperty(value = "subscription")
    private Subscription subscription;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public UUID id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the ResolvedSubscription object itself.
     */
    public ResolvedSubscription withId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Get the subscriptionName value.
     *
     * @return the subscriptionName value
     */
    public String subscriptionName() {
        return this.subscriptionName;
    }

    /**
     * Set the subscriptionName value.
     *
     * @param subscriptionName the subscriptionName value to set
     * @return the ResolvedSubscription object itself.
     */
    public ResolvedSubscription withSubscriptionName(String subscriptionName) {
        this.subscriptionName = subscriptionName;
        return this;
    }

    /**
     * Get the offerId value.
     *
     * @return the offerId value
     */
    public String offerId() {
        return this.offerId;
    }

    /**
     * Set the offerId value.
     *
     * @param offerId the offerId value to set
     * @return the ResolvedSubscription object itself.
     */
    public ResolvedSubscription withOfferId(String offerId) {
        this.offerId = offerId;
        return this;
    }

    /**
     * Get the planId value.
     *
     * @return the planId value
     */
    public String planId() {
        return this.planId;
    }

    /**
     * Set the planId value.
     *
     * @param planId the planId value to set
     * @return the ResolvedSubscription object itself.
     */
    public ResolvedSubscription withPlanId(String planId) {
        this.planId = planId;
        return this;
    }

    /**
     * Get the quantity value.
     *
     * @return the quantity value
     */
    public Long quantity() {
        return this.quantity;
    }

    /**
     * Set the quantity value.
     *
     * @param quantity the quantity value to set
     * @return the ResolvedSubscription object itself.
     */
    public ResolvedSubscription withQuantity(Long quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Get the subscription value.
     *
     * @return the subscription value
     */
    public Subscription subscription() {
        return this.subscription;
    }

    /**
     * Set the subscription value.
     *
     * @param subscription the subscription value to set
     * @return the ResolvedSubscription object itself.
     */
    public ResolvedSubscription withSubscription(Subscription subscription) {
        this.subscription = subscription;
        return this;
    }

}
