/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SubscriptionPlans model.
 */
public class SubscriptionPlans {
    /**
     * The plans property.
     */
    @JsonProperty(value = "plans")
    private List<Plan> plans;

    /**
     * Get the plans value.
     *
     * @return the plans value
     */
    public List<Plan> plans() {
        return this.plans;
    }

    /**
     * Set the plans value.
     *
     * @param plans the plans value to set
     * @return the SubscriptionPlans object itself.
     */
    public SubscriptionPlans withPlans(List<Plan> plans) {
        this.plans = plans;
        return this;
    }

}
