/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import java.util.UUID;
import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The UsageEvent model.
 */
public class UsageEvent {
    /**
     * Subscription ID for the event.
     */
    @JsonProperty(value = "resourceId")
    private UUID resourceId;

    /**
     * Number of units consumed.
     */
    @JsonProperty(value = "quantity")
    private Long quantity;

    /**
     * Dimension identifier.
     */
    @JsonProperty(value = "dimension")
    private String dimension;

    /**
     * Time in UTC when the usage event occurred.
     */
    @JsonProperty(value = "effectiveStartTime")
    private DateTime effectiveStartTime;

    /**
     * Plan associated with the purchased offer.
     */
    @JsonProperty(value = "planId")
    private String planId;

    /**
     * Get subscription ID for the event.
     *
     * @return the resourceId value
     */
    public UUID resourceId() {
        return this.resourceId;
    }

    /**
     * Set subscription ID for the event.
     *
     * @param resourceId the resourceId value to set
     * @return the UsageEvent object itself.
     */
    public UsageEvent withResourceId(UUID resourceId) {
        this.resourceId = resourceId;
        return this;
    }

    /**
     * Get number of units consumed.
     *
     * @return the quantity value
     */
    public Long quantity() {
        return this.quantity;
    }

    /**
     * Set number of units consumed.
     *
     * @param quantity the quantity value to set
     * @return the UsageEvent object itself.
     */
    public UsageEvent withQuantity(Long quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Get dimension identifier.
     *
     * @return the dimension value
     */
    public String dimension() {
        return this.dimension;
    }

    /**
     * Set dimension identifier.
     *
     * @param dimension the dimension value to set
     * @return the UsageEvent object itself.
     */
    public UsageEvent withDimension(String dimension) {
        this.dimension = dimension;
        return this;
    }

    /**
     * Get time in UTC when the usage event occurred.
     *
     * @return the effectiveStartTime value
     */
    public DateTime effectiveStartTime() {
        return this.effectiveStartTime;
    }

    /**
     * Set time in UTC when the usage event occurred.
     *
     * @param effectiveStartTime the effectiveStartTime value to set
     * @return the UsageEvent object itself.
     */
    public UsageEvent withEffectiveStartTime(DateTime effectiveStartTime) {
        this.effectiveStartTime = effectiveStartTime;
        return this;
    }

    /**
     * Get plan associated with the purchased offer.
     *
     * @return the planId value
     */
    public String planId() {
        return this.planId;
    }

    /**
     * Set plan associated with the purchased offer.
     *
     * @param planId the planId value to set
     * @return the UsageEvent object itself.
     */
    public UsageEvent withPlanId(String planId) {
        this.planId = planId;
        return this;
    }

}
