/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The UsageEventConflictResponse model.
 */
public class UsageEventConflictResponse {
    /**
     * The code property.
     */
    @JsonProperty(value = "code")
    private String code;

    /**
     * The additionalInfo property.
     */
    @JsonProperty(value = "additionalInfo")
    private UsageEventConflictResponseAdditionalInfo additionalInfo;

    /**
     * Get the code value.
     *
     * @return the code value
     */
    public String code() {
        return this.code;
    }

    /**
     * Set the code value.
     *
     * @param code the code value to set
     * @return the UsageEventConflictResponse object itself.
     */
    public UsageEventConflictResponse withCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get the additionalInfo value.
     *
     * @return the additionalInfo value
     */
    public UsageEventConflictResponseAdditionalInfo additionalInfo() {
        return this.additionalInfo;
    }

    /**
     * Set the additionalInfo value.
     *
     * @param additionalInfo the additionalInfo value to set
     * @return the UsageEventConflictResponse object itself.
     */
    public UsageEventConflictResponse withAdditionalInfo(UsageEventConflictResponseAdditionalInfo additionalInfo) {
        this.additionalInfo = additionalInfo;
        return this;
    }

}
