// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.meter.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The BatchUsageEvent model. */
@Fluent
public final class BatchUsageEvent {
    /*
     * The request property.
     */
    @JsonProperty(value = "request")
    private List<UsageEvent> request;

    /**
     * Get the request property: The request property.
     *
     * @return the request value.
     */
    public List<UsageEvent> getRequest() {
        return this.request;
    }

    /**
     * Set the request property: The request property.
     *
     * @param request the request value to set.
     * @return the BatchUsageEvent object itself.
     */
    public BatchUsageEvent setRequest(List<UsageEvent> request) {
        this.request = request;
        return this;
    }
}
