// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.meter.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The BatchUsageEventOkResponse model. */
@Fluent
public final class BatchUsageEventOkResponse {
    /*
     * The result property.
     */
    @JsonProperty(value = "result")
    private List<UsageBatchEventOkMessage> result;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Integer count;

    /**
     * Get the result property: The result property.
     *
     * @return the result value.
     */
    public List<UsageBatchEventOkMessage> getResult() {
        return this.result;
    }

    /**
     * Set the result property: The result property.
     *
     * @param result the result value to set.
     * @return the BatchUsageEventOkResponse object itself.
     */
    public BatchUsageEventOkResponse setResult(List<UsageBatchEventOkMessage> result) {
        this.result = result;
        return this;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Integer getCount() {
        return this.count;
    }

    /**
     * Set the count property: The count property.
     *
     * @param count the count value to set.
     * @return the BatchUsageEventOkResponse object itself.
     */
    public BatchUsageEventOkResponse setCount(Integer count) {
        this.count = count;
        return this;
    }
}
