// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

/**
 * Package containing the data models for MeteringAPI. With the commercial marketplace metering service, you can create
 * software as a service (SaaS) and managed application offers which charge according to non-standard units. Before
 * publishing an offer to the commercial marketplace, you define the billing dimensions such as bandwidth, tickets, or
 * emails processed. Customers then pay according to their consumption of these dimensions, with your system informing
 * Microsoft via the commercial marketplace metering service API of billable events.
 */
package com.microsoft.marketplace.meter.models;
