// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.meter.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.UUID;

/** The UsageEvent model. */
@Fluent
public final class UsageEvent {
    /*
     * subscriptionId property value for SaaS offer subscriptions;
     * resourceUsageId property on the managed application resource for managed
     * application offers. For managed applications, only use one of resourceId
     * or resourceUri.
     */
    @JsonProperty(value = "resourceId")
    private UUID resourceId;

    /*
     * Resource URI for the managed app. Used with managed applications. Only
     * use resourceUri or resourceId, but never both.
     */
    @JsonProperty(value = "resourceUri")
    private String resourceUri;

    /*
     * Number of units consumed
     */
    @JsonProperty(value = "quantity")
    private Double quantity;

    /*
     * Dimension identifier
     */
    @JsonProperty(value = "dimension")
    private String dimension;

    /*
     * Time in UTC when the usage event occurred
     */
    @JsonProperty(value = "effectiveStartTime")
    private OffsetDateTime effectiveStartTime;

    /*
     * Plan associated with the purchased offer
     */
    @JsonProperty(value = "planId")
    private String planId;

    /**
     * Get the resourceId property: subscriptionId property value for SaaS offer subscriptions; resourceUsageId property
     * on the managed application resource for managed application offers. For managed applications, only use one of
     * resourceId or resourceUri.
     *
     * @return the resourceId value.
     */
    public UUID getResourceId() {
        return this.resourceId;
    }

    /**
     * Set the resourceId property: subscriptionId property value for SaaS offer subscriptions; resourceUsageId property
     * on the managed application resource for managed application offers. For managed applications, only use one of
     * resourceId or resourceUri.
     *
     * @param resourceId the resourceId value to set.
     * @return the UsageEvent object itself.
     */
    public UsageEvent setResourceId(UUID resourceId) {
        this.resourceId = resourceId;
        return this;
    }

    /**
     * Get the resourceUri property: Resource URI for the managed app. Used with managed applications. Only use
     * resourceUri or resourceId, but never both.
     *
     * @return the resourceUri value.
     */
    public String getResourceUri() {
        return this.resourceUri;
    }

    /**
     * Set the resourceUri property: Resource URI for the managed app. Used with managed applications. Only use
     * resourceUri or resourceId, but never both.
     *
     * @param resourceUri the resourceUri value to set.
     * @return the UsageEvent object itself.
     */
    public UsageEvent setResourceUri(String resourceUri) {
        this.resourceUri = resourceUri;
        return this;
    }

    /**
     * Get the quantity property: Number of units consumed.
     *
     * @return the quantity value.
     */
    public Double getQuantity() {
        return this.quantity;
    }

    /**
     * Set the quantity property: Number of units consumed.
     *
     * @param quantity the quantity value to set.
     * @return the UsageEvent object itself.
     */
    public UsageEvent setQuantity(Double quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Get the dimension property: Dimension identifier.
     *
     * @return the dimension value.
     */
    public String getDimension() {
        return this.dimension;
    }

    /**
     * Set the dimension property: Dimension identifier.
     *
     * @param dimension the dimension value to set.
     * @return the UsageEvent object itself.
     */
    public UsageEvent setDimension(String dimension) {
        this.dimension = dimension;
        return this;
    }

    /**
     * Get the effectiveStartTime property: Time in UTC when the usage event occurred.
     *
     * @return the effectiveStartTime value.
     */
    public OffsetDateTime getEffectiveStartTime() {
        return this.effectiveStartTime;
    }

    /**
     * Set the effectiveStartTime property: Time in UTC when the usage event occurred.
     *
     * @param effectiveStartTime the effectiveStartTime value to set.
     * @return the UsageEvent object itself.
     */
    public UsageEvent setEffectiveStartTime(OffsetDateTime effectiveStartTime) {
        this.effectiveStartTime = effectiveStartTime;
        return this;
    }

    /**
     * Get the planId property: Plan associated with the purchased offer.
     *
     * @return the planId value.
     */
    public String getPlanId() {
        return this.planId;
    }

    /**
     * Set the planId property: Plan associated with the purchased offer.
     *
     * @param planId the planId value to set.
     * @return the UsageEvent object itself.
     */
    public UsageEvent setPlanId(String planId) {
        this.planId = planId;
        return this;
    }
}
