// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.meter.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.UUID;

/** The UsageBatchEventOkMessage model. */
@Fluent
public final class UsageBatchEventOkMessage {
    /*
     * Unique identifier associated with the usage event
     */
    @JsonProperty(value = "usageEventId")
    private UUID usageEventId;

    /*
     * Status of the operation.
     */
    @JsonProperty(value = "status")
    private UsageEventStatusEnum status;

    /*
     * Time this message was created in UTC
     */
    @JsonProperty(value = "messageTime")
    private OffsetDateTime messageTime;

    /*
     * Identifier of the resource against which usage is emitted
     */
    @JsonProperty(value = "resourceId")
    private UUID resourceId;

    /*
     * Identifier of the managed app resource against which usage is emitted
     */
    @JsonProperty(value = "resourceUri")
    private String resourceUri;

    /*
     * Number of units consumed
     */
    @JsonProperty(value = "quantity")
    private Double quantity;

    /*
     * Dimension identifier
     */
    @JsonProperty(value = "dimension")
    private String dimension;

    /*
     * Time in UTC when the usage event occurred
     */
    @JsonProperty(value = "effectiveStartTime")
    private OffsetDateTime effectiveStartTime;

    /*
     * Plan associated with the purchased offer
     */
    @JsonProperty(value = "planId")
    private String planId;

    /*
     * The error property.
     */
    @JsonProperty(value = "error")
    private UsageEventConflictResponse error;

    /**
     * Get the usageEventId property: Unique identifier associated with the usage event.
     *
     * @return the usageEventId value.
     */
    public UUID getUsageEventId() {
        return this.usageEventId;
    }

    /**
     * Set the usageEventId property: Unique identifier associated with the usage event.
     *
     * @param usageEventId the usageEventId value to set.
     * @return the UsageBatchEventOkMessage object itself.
     */
    public UsageBatchEventOkMessage setUsageEventId(UUID usageEventId) {
        this.usageEventId = usageEventId;
        return this;
    }

    /**
     * Get the status property: Status of the operation.
     *
     * @return the status value.
     */
    public UsageEventStatusEnum getStatus() {
        return this.status;
    }

    /**
     * Set the status property: Status of the operation.
     *
     * @param status the status value to set.
     * @return the UsageBatchEventOkMessage object itself.
     */
    public UsageBatchEventOkMessage setStatus(UsageEventStatusEnum status) {
        this.status = status;
        return this;
    }

    /**
     * Get the messageTime property: Time this message was created in UTC.
     *
     * @return the messageTime value.
     */
    public OffsetDateTime getMessageTime() {
        return this.messageTime;
    }

    /**
     * Set the messageTime property: Time this message was created in UTC.
     *
     * @param messageTime the messageTime value to set.
     * @return the UsageBatchEventOkMessage object itself.
     */
    public UsageBatchEventOkMessage setMessageTime(OffsetDateTime messageTime) {
        this.messageTime = messageTime;
        return this;
    }

    /**
     * Get the resourceId property: Identifier of the resource against which usage is emitted.
     *
     * @return the resourceId value.
     */
    public UUID getResourceId() {
        return this.resourceId;
    }

    /**
     * Set the resourceId property: Identifier of the resource against which usage is emitted.
     *
     * @param resourceId the resourceId value to set.
     * @return the UsageBatchEventOkMessage object itself.
     */
    public UsageBatchEventOkMessage setResourceId(UUID resourceId) {
        this.resourceId = resourceId;
        return this;
    }

    /**
     * Get the resourceUri property: Identifier of the managed app resource against which usage is emitted.
     *
     * @return the resourceUri value.
     */
    public String getResourceUri() {
        return this.resourceUri;
    }

    /**
     * Set the resourceUri property: Identifier of the managed app resource against which usage is emitted.
     *
     * @param resourceUri the resourceUri value to set.
     * @return the UsageBatchEventOkMessage object itself.
     */
    public UsageBatchEventOkMessage setResourceUri(String resourceUri) {
        this.resourceUri = resourceUri;
        return this;
    }

    /**
     * Get the quantity property: Number of units consumed.
     *
     * @return the quantity value.
     */
    public Double getQuantity() {
        return this.quantity;
    }

    /**
     * Set the quantity property: Number of units consumed.
     *
     * @param quantity the quantity value to set.
     * @return the UsageBatchEventOkMessage object itself.
     */
    public UsageBatchEventOkMessage setQuantity(Double quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Get the dimension property: Dimension identifier.
     *
     * @return the dimension value.
     */
    public String getDimension() {
        return this.dimension;
    }

    /**
     * Set the dimension property: Dimension identifier.
     *
     * @param dimension the dimension value to set.
     * @return the UsageBatchEventOkMessage object itself.
     */
    public UsageBatchEventOkMessage setDimension(String dimension) {
        this.dimension = dimension;
        return this;
    }

    /**
     * Get the effectiveStartTime property: Time in UTC when the usage event occurred.
     *
     * @return the effectiveStartTime value.
     */
    public OffsetDateTime getEffectiveStartTime() {
        return this.effectiveStartTime;
    }

    /**
     * Set the effectiveStartTime property: Time in UTC when the usage event occurred.
     *
     * @param effectiveStartTime the effectiveStartTime value to set.
     * @return the UsageBatchEventOkMessage object itself.
     */
    public UsageBatchEventOkMessage setEffectiveStartTime(OffsetDateTime effectiveStartTime) {
        this.effectiveStartTime = effectiveStartTime;
        return this;
    }

    /**
     * Get the planId property: Plan associated with the purchased offer.
     *
     * @return the planId value.
     */
    public String getPlanId() {
        return this.planId;
    }

    /**
     * Set the planId property: Plan associated with the purchased offer.
     *
     * @param planId the planId value to set.
     * @return the UsageBatchEventOkMessage object itself.
     */
    public UsageBatchEventOkMessage setPlanId(String planId) {
        this.planId = planId;
        return this;
    }

    /**
     * Get the error property: The error property.
     *
     * @return the error value.
     */
    public UsageEventConflictResponse getError() {
        return this.error;
    }

    /**
     * Set the error property: The error property.
     *
     * @param error the error value to set.
     * @return the UsageBatchEventOkMessage object itself.
     */
    public UsageBatchEventOkMessage setError(UsageEventConflictResponse error) {
        this.error = error;
        return this;
    }
}
