// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.meter.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The UsageEventConflictResponseAdditionalInfo model. */
@Fluent
public final class UsageEventConflictResponseAdditionalInfo {
    /*
     * The acceptedMessage property.
     */
    @JsonProperty(value = "acceptedMessage")
    private UsageEventOkResponse acceptedMessage;

    /**
     * Get the acceptedMessage property: The acceptedMessage property.
     *
     * @return the acceptedMessage value.
     */
    public UsageEventOkResponse getAcceptedMessage() {
        return this.acceptedMessage;
    }

    /**
     * Set the acceptedMessage property: The acceptedMessage property.
     *
     * @param acceptedMessage the acceptedMessage value to set.
     * @return the UsageEventConflictResponseAdditionalInfo object itself.
     */
    public UsageEventConflictResponseAdditionalInfo setAcceptedMessage(UsageEventOkResponse acceptedMessage) {
        this.acceptedMessage = acceptedMessage;
        return this;
    }
}
