// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.microsoft.marketplace.meter.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for UsageEventConflictResponseAdditionalInfoStatus. */
public final class UsageEventConflictResponseAdditionalInfoStatus
        extends ExpandableStringEnum<UsageEventConflictResponseAdditionalInfoStatus> {
    /** Static value Accepted for UsageEventConflictResponseAdditionalInfoStatus. */
    public static final UsageEventConflictResponseAdditionalInfoStatus ACCEPTED = fromString("Accepted");

    /** Static value NotProcessed for UsageEventConflictResponseAdditionalInfoStatus. */
    public static final UsageEventConflictResponseAdditionalInfoStatus NOT_PROCESSED = fromString("NotProcessed");

    /** Static value Expired for UsageEventConflictResponseAdditionalInfoStatus. */
    public static final UsageEventConflictResponseAdditionalInfoStatus EXPIRED = fromString("Expired");

    /**
     * Creates or finds a UsageEventConflictResponseAdditionalInfoStatus from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding UsageEventConflictResponseAdditionalInfoStatus.
     */
    @JsonCreator
    public static UsageEventConflictResponseAdditionalInfoStatus fromString(String name) {
        return fromString(name, UsageEventConflictResponseAdditionalInfoStatus.class);
    }

    /** @return known UsageEventConflictResponseAdditionalInfoStatus values. */
    public static Collection<UsageEventConflictResponseAdditionalInfoStatus> values() {
        return values(UsageEventConflictResponseAdditionalInfoStatus.class);
    }
}
