/*
 * SaaS fulfillment APIs, version 2
 * This spec details the APIs that enable partners to sell their SaaS applications in the AppSource marketplace and the Azure Marketplace. These APIs are a requirement for transactable SaaS offers on the AppSource and Azure Marketplace.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT license.
 */

package com.azure.marketplace;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Version of the API. Use 2018-08-31 for production, 2018-09-15 for the Mock API.
 */
@JsonAdapter(ApiVersion.Adapter.class)
public enum ApiVersion {
  _08_31("2018-08-31"),
  _09_15("2018-09-15");

  private String value;

  ApiVersion(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ApiVersion fromValue(String text) {
    for (ApiVersion b : ApiVersion.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ApiVersion> {
    @Override
    public void write(final JsonWriter jsonWriter, final ApiVersion enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ApiVersion read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ApiVersion.fromValue(String.valueOf(value));
    }
  }
}
