// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.azure.marketplace;

import com.azure.core.annotation.ServiceClientBuilder;
import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.CookiePolicy;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;

/** A builder for creating a new instance of the SaaSFulfillmentAPIsVersion2 type. */
@ServiceClientBuilder(serviceClients = {SaaSFulfillmentAPIsVersion2.class})
public final class SaaSFulfillmentAPIsVersion2Builder {
    /*
     * server parameter
     */
    private String host;

    /**
     * Sets server parameter.
     *
     * @param host the host value.
     * @return the SaaSFulfillmentAPIsVersion2Builder.
     */
    public SaaSFulfillmentAPIsVersion2Builder host(String host) {
        this.host = host;
        return this;
    }

    /*
     * The HTTP pipeline to send requests through
     */
    private HttpPipeline pipeline;

    /**
     * Sets The HTTP pipeline to send requests through.
     *
     * @param pipeline the pipeline value.
     * @return the SaaSFulfillmentAPIsVersion2Builder.
     */
    public SaaSFulfillmentAPIsVersion2Builder pipeline(HttpPipeline pipeline) {
        this.pipeline = pipeline;
        return this;
    }

    /**
     * Builds an instance of SaaSFulfillmentAPIsVersion2 with the provided parameters.
     *
     * @return an instance of SaaSFulfillmentAPIsVersion2.
     */
    public SaaSFulfillmentAPIsVersion2 buildClient() {
        if (host == null) {
            this.host = "https://marketplaceapi.microsoft.com/api";
        }
        if (pipeline == null) {
            this.pipeline =
                    new HttpPipelineBuilder()
                            .policies(new UserAgentPolicy(), new RetryPolicy(), new CookiePolicy())
                            .build();
        }
        SaaSFulfillmentAPIsVersion2 client = new SaaSFulfillmentAPIsVersion2(pipeline, host);
        return client;
    }
}
