/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The AadIdentifier model.
 */
public class AadIdentifier {
    /**
     * The emailId property.
     */
    @JsonProperty(value = "emailId")
    private String emailId;

    /**
     * The objectId property.
     */
    @JsonProperty(value = "objectId")
    private UUID objectId;

    /**
     * The tenantId property.
     */
    @JsonProperty(value = "tenantId")
    private UUID tenantId;

    /**
     * The puid property.
     */
    @JsonProperty(value = "puid")
    private String puid;

    /**
     * Get the emailId value.
     *
     * @return the emailId value
     */
    public String emailId() {
        return this.emailId;
    }

    /**
     * Set the emailId value.
     *
     * @param emailId the emailId value to set
     * @return the AadIdentifier object itself.
     */
    public AadIdentifier withEmailId(String emailId) {
        this.emailId = emailId;
        return this;
    }

    /**
     * Get the objectId value.
     *
     * @return the objectId value
     */
    public UUID objectId() {
        return this.objectId;
    }

    /**
     * Set the objectId value.
     *
     * @param objectId the objectId value to set
     * @return the AadIdentifier object itself.
     */
    public AadIdentifier withObjectId(UUID objectId) {
        this.objectId = objectId;
        return this;
    }

    /**
     * Get the tenantId value.
     *
     * @return the tenantId value
     */
    public UUID tenantId() {
        return this.tenantId;
    }

    /**
     * Set the tenantId value.
     *
     * @param tenantId the tenantId value to set
     * @return the AadIdentifier object itself.
     */
    public AadIdentifier withTenantId(UUID tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    /**
     * Get the puid value.
     *
     * @return the puid value
     */
    public String puid() {
        return this.puid;
    }

    /**
     * Set the puid value.
     *
     * @param puid the puid value to set
     * @return the AadIdentifier object itself.
     */
    public AadIdentifier withPuid(String puid) {
        this.puid = puid;
        return this;
    }

}
