// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.azure.marketplace.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for ApiVersion. */
public final class ApiVersion extends ExpandableStringEnum<ApiVersion> {
    /** Static value 2018-08-31 for ApiVersion. */
    public static final ApiVersion TWO_ZERO_ONE_EIGHT_ZERO_EIGHT_THREE_ONE = fromString("2018-08-31");

    /** Static value 2018-09-15 for ApiVersion. */
    public static final ApiVersion TWO_ZERO_ONE_EIGHT_ZERO_NINE_ONE_FIVE = fromString("2018-09-15");

    /**
     * Creates or finds a ApiVersion from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding ApiVersion.
     */
    @JsonCreator
    public static ApiVersion fromString(String name) {
        return fromString(name, ApiVersion.class);
    }

    /** @return known ApiVersion values. */
    public static Collection<ApiVersion> values() {
        return values(ApiVersion.class);
    }
}
