/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines headers for UpdateSubscription operation.
 */
public class FulfillmentOperationsUpdateSubscriptionHeaders {
    /**
     * The operationLocationUri property.
     */
    @JsonProperty(value = "Operation-Location")
    private String operationLocationUri;

    /**
     * Get the operationLocationUri value.
     *
     * @return the operationLocationUri value
     */
    public String operationLocationUri() {
        return this.operationLocationUri;
    }

    /**
     * Set the operationLocationUri value.
     *
     * @param operationLocationUri the operationLocationUri value to set
     * @return the FulfillmentOperationsUpdateSubscriptionHeaders object itself.
     */
    public FulfillmentOperationsUpdateSubscriptionHeaders withOperationLocationUri(String operationLocationUri) {
        this.operationLocationUri = operationLocationUri;
        return this;
    }

}
