/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import java.util.UUID;
import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Operation model.
 */
public class Operation {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private UUID id;

    /**
     * The activityId property.
     */
    @JsonProperty(value = "activityId")
    private UUID activityId;

    /**
     * The subscriptionId property.
     */
    @JsonProperty(value = "subscriptionId")
    private UUID subscriptionId;

    /**
     * The offerId property.
     */
    @JsonProperty(value = "offerId")
    private String offerId;

    /**
     * The publisherId property.
     */
    @JsonProperty(value = "publisherId")
    private String publisherId;

    /**
     * The planId property.
     */
    @JsonProperty(value = "planId")
    private String planId;

    /**
     * The quantity property.
     */
    @JsonProperty(value = "quantity")
    private Integer quantity;

    /**
     * Possible values include: 'Unsubscribe', 'ChangePlan', 'ChangeQuantity',
     * 'Suspend', 'Reinstate'.
     */
    @JsonProperty(value = "action")
    private OperationActionEnum action;

    /**
     * The timeStamp property.
     */
    @JsonProperty(value = "timeStamp")
    private DateTime timeStamp;

    /**
     * Possible values include: 'NotStarted', 'InProgress', 'Succeeded',
     * 'Failed', 'Conflict'.
     */
    @JsonProperty(value = "status")
    private OperationStatusEnum status;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public UUID id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the Operation object itself.
     */
    public Operation withId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Get the activityId value.
     *
     * @return the activityId value
     */
    public UUID activityId() {
        return this.activityId;
    }

    /**
     * Set the activityId value.
     *
     * @param activityId the activityId value to set
     * @return the Operation object itself.
     */
    public Operation withActivityId(UUID activityId) {
        this.activityId = activityId;
        return this;
    }

    /**
     * Get the subscriptionId value.
     *
     * @return the subscriptionId value
     */
    public UUID subscriptionId() {
        return this.subscriptionId;
    }

    /**
     * Set the subscriptionId value.
     *
     * @param subscriptionId the subscriptionId value to set
     * @return the Operation object itself.
     */
    public Operation withSubscriptionId(UUID subscriptionId) {
        this.subscriptionId = subscriptionId;
        return this;
    }

    /**
     * Get the offerId value.
     *
     * @return the offerId value
     */
    public String offerId() {
        return this.offerId;
    }

    /**
     * Set the offerId value.
     *
     * @param offerId the offerId value to set
     * @return the Operation object itself.
     */
    public Operation withOfferId(String offerId) {
        this.offerId = offerId;
        return this;
    }

    /**
     * Get the publisherId value.
     *
     * @return the publisherId value
     */
    public String publisherId() {
        return this.publisherId;
    }

    /**
     * Set the publisherId value.
     *
     * @param publisherId the publisherId value to set
     * @return the Operation object itself.
     */
    public Operation withPublisherId(String publisherId) {
        this.publisherId = publisherId;
        return this;
    }

    /**
     * Get the planId value.
     *
     * @return the planId value
     */
    public String planId() {
        return this.planId;
    }

    /**
     * Set the planId value.
     *
     * @param planId the planId value to set
     * @return the Operation object itself.
     */
    public Operation withPlanId(String planId) {
        this.planId = planId;
        return this;
    }

    /**
     * Get the quantity value.
     *
     * @return the quantity value
     */
    public Integer quantity() {
        return this.quantity;
    }

    /**
     * Set the quantity value.
     *
     * @param quantity the quantity value to set
     * @return the Operation object itself.
     */
    public Operation withQuantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Get possible values include: 'Unsubscribe', 'ChangePlan', 'ChangeQuantity', 'Suspend', 'Reinstate'.
     *
     * @return the action value
     */
    public OperationActionEnum action() {
        return this.action;
    }

    /**
     * Set possible values include: 'Unsubscribe', 'ChangePlan', 'ChangeQuantity', 'Suspend', 'Reinstate'.
     *
     * @param action the action value to set
     * @return the Operation object itself.
     */
    public Operation withAction(OperationActionEnum action) {
        this.action = action;
        return this;
    }

    /**
     * Get the timeStamp value.
     *
     * @return the timeStamp value
     */
    public DateTime timeStamp() {
        return this.timeStamp;
    }

    /**
     * Set the timeStamp value.
     *
     * @param timeStamp the timeStamp value to set
     * @return the Operation object itself.
     */
    public Operation withTimeStamp(DateTime timeStamp) {
        this.timeStamp = timeStamp;
        return this;
    }

    /**
     * Get possible values include: 'NotStarted', 'InProgress', 'Succeeded', 'Failed', 'Conflict'.
     *
     * @return the status value
     */
    public OperationStatusEnum status() {
        return this.status;
    }

    /**
     * Set possible values include: 'NotStarted', 'InProgress', 'Succeeded', 'Failed', 'Conflict'.
     *
     * @param status the status value to set
     * @return the Operation object itself.
     */
    public Operation withStatus(OperationStatusEnum status) {
        this.status = status;
        return this;
    }

}
