/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The OperationList model.
 */
public class OperationList {
    /**
     * The operations property.
     */
    @JsonProperty(value = "operations")
    private List<Operation> operations;

    /**
     * Get the operations value.
     *
     * @return the operations value
     */
    public List<Operation> operations() {
        return this.operations;
    }

    /**
     * Set the operations value.
     *
     * @param operations the operations value to set
     * @return the OperationList object itself.
     */
    public OperationList withOperations(List<Operation> operations) {
        this.operations = operations;
        return this;
    }

}
