/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for OperationStatusEnum.
 */
public enum OperationStatusEnum {
    /** Enum value NotStarted. */
    NOT_STARTED("NotStarted"),

    /** Enum value InProgress. */
    IN_PROGRESS("InProgress"),

    /** Enum value Succeeded. */
    SUCCEEDED("Succeeded"),

    /** Enum value Failed. */
    FAILED("Failed"),

    /** Enum value Conflict. */
    CONFLICT("Conflict");

    /** The actual serialized value for a OperationStatusEnum instance. */
    private String value;

    OperationStatusEnum(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a OperationStatusEnum instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed OperationStatusEnum object, or null if unable to parse.
     */
    @JsonCreator
    public static OperationStatusEnum fromString(String value) {
        OperationStatusEnum[] items = OperationStatusEnum.values();
        for (OperationStatusEnum item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
