// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

/**
 * Package containing the data models for SaaSFulfillmentAPIsVersion2. This spec details the APIs that enable partners
 * to sell their SaaS applications in the AppSource marketplace and the Azure Marketplace. These APIs are a requirement
 * for transactable SaaS offers on the AppSource and Azure Marketplace.
 */
package com.azure.marketplace.models;
