/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Plan model.
 */
public class Plan {
    /**
     * The planId property.
     */
    @JsonProperty(value = "planId")
    private String planId;

    /**
     * The displayName property.
     */
    @JsonProperty(value = "displayName")
    private String displayName;

    /**
     * The isPrivate property.
     */
    @JsonProperty(value = "isPrivate")
    private Boolean isPrivate;

    /**
     * Get the planId value.
     *
     * @return the planId value
     */
    public String planId() {
        return this.planId;
    }

    /**
     * Set the planId value.
     *
     * @param planId the planId value to set
     * @return the Plan object itself.
     */
    public Plan withPlanId(String planId) {
        this.planId = planId;
        return this;
    }

    /**
     * Get the displayName value.
     *
     * @return the displayName value
     */
    public String displayName() {
        return this.displayName;
    }

    /**
     * Set the displayName value.
     *
     * @param displayName the displayName value to set
     * @return the Plan object itself.
     */
    public Plan withDisplayName(String displayName) {
        this.displayName = displayName;
        return this;
    }

    /**
     * Get the isPrivate value.
     *
     * @return the isPrivate value
     */
    public Boolean isPrivate() {
        return this.isPrivate;
    }

    /**
     * Set the isPrivate value.
     *
     * @param isPrivate the isPrivate value to set
     * @return the Plan object itself.
     */
    public Plan withIsPrivate(Boolean isPrivate) {
        this.isPrivate = isPrivate;
        return this;
    }

}
