// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package com.azure.marketplace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Defines values for SessionModeEnum. */
public enum SessionModeEnum {
    /** Enum value None. */
    NONE("None"),

    /** Enum value DryRun. */
    DRY_RUN("DryRun");

    /** The actual serialized value for a SessionModeEnum instance. */
    private final String value;

    SessionModeEnum(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a SessionModeEnum instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed SessionModeEnum object, or null if unable to parse.
     */
    @JsonCreator
    public static SessionModeEnum fromString(String value) {
        SessionModeEnum[] items = SessionModeEnum.values();
        for (SessionModeEnum item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
