/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import java.util.UUID;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Subscription model.
 */
public class Subscription {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private UUID id;

    /**
     * The publisherId property.
     */
    @JsonProperty(value = "publisherId")
    private String publisherId;

    /**
     * The offerId property.
     */
    @JsonProperty(value = "offerId")
    private String offerId;

    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Indicates the status of the operation. Possible values include:
     * 'NotStarted', 'PendingFulfillmentStart', 'Subscribed', 'Suspended',
     * 'Unsubscribed'.
     */
    @JsonProperty(value = "saasSubscriptionStatus")
    private SubscriptionStatusEnum saasSubscriptionStatus;

    /**
     * The beneficiary property.
     */
    @JsonProperty(value = "beneficiary")
    private AadIdentifier beneficiary;

    /**
     * The purchaser property.
     */
    @JsonProperty(value = "purchaser")
    private AadIdentifier purchaser;

    /**
     * The planId property.
     */
    @JsonProperty(value = "planId")
    private String planId;

    /**
     * The quantity property.
     */
    @JsonProperty(value = "quantity")
    private Integer quantity;

    /**
     * The term property.
     */
    @JsonProperty(value = "term")
    private SubscriptionTerm term;

    /**
     * Indicating whether the current subscription is a test asset.
     */
    @JsonProperty(value = "isTest")
    private Boolean isTest;

    /**
     * true - the customer subscription is currently in free trial, false - the
     * customer subscription is not currently in free trial.(optional field -
     * default false).
     */
    @JsonProperty(value = "isFreeTrial")
    private Boolean isFreeTrial;

    /**
     * The allowedCustomerOperations property.
     */
    @JsonProperty(value = "allowedCustomerOperations")
    private List<AllowedCustomerOperationsEnum> allowedCustomerOperations;

    /**
     * The sessionId property.
     */
    @JsonProperty(value = "sessionId")
    private UUID sessionId;

    /**
     * The fulfillmentId property.
     */
    @JsonProperty(value = "fulfillmentId")
    private UUID fulfillmentId;

    /**
     * The storeFront property.
     */
    @JsonProperty(value = "storeFront")
    private String storeFront;

    /**
     * Dry Run indicates all transactions run as Test-Mode in the commerce
     * stack. Possible values include: 'None', 'DryRun'.
     */
    @JsonProperty(value = "sessionMode")
    private SessionModeEnum sessionMode;

    /**
     * Possible Values are None, Csp (Csp sandbox purchase). Possible values
     * include: 'None', 'Csp'.
     */
    @JsonProperty(value = "sandboxType")
    private SandboxTypeEnum sandboxType;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public UUID id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the Subscription object itself.
     */
    public Subscription withId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Get the publisherId value.
     *
     * @return the publisherId value
     */
    public String publisherId() {
        return this.publisherId;
    }

    /**
     * Set the publisherId value.
     *
     * @param publisherId the publisherId value to set
     * @return the Subscription object itself.
     */
    public Subscription withPublisherId(String publisherId) {
        this.publisherId = publisherId;
        return this;
    }

    /**
     * Get the offerId value.
     *
     * @return the offerId value
     */
    public String offerId() {
        return this.offerId;
    }

    /**
     * Set the offerId value.
     *
     * @param offerId the offerId value to set
     * @return the Subscription object itself.
     */
    public Subscription withOfferId(String offerId) {
        this.offerId = offerId;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the Subscription object itself.
     */
    public Subscription withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get indicates the status of the operation. Possible values include: 'NotStarted', 'PendingFulfillmentStart', 'Subscribed', 'Suspended', 'Unsubscribed'.
     *
     * @return the saasSubscriptionStatus value
     */
    public SubscriptionStatusEnum saasSubscriptionStatus() {
        return this.saasSubscriptionStatus;
    }

    /**
     * Set indicates the status of the operation. Possible values include: 'NotStarted', 'PendingFulfillmentStart', 'Subscribed', 'Suspended', 'Unsubscribed'.
     *
     * @param saasSubscriptionStatus the saasSubscriptionStatus value to set
     * @return the Subscription object itself.
     */
    public Subscription withSaasSubscriptionStatus(SubscriptionStatusEnum saasSubscriptionStatus) {
        this.saasSubscriptionStatus = saasSubscriptionStatus;
        return this;
    }

    /**
     * Get the beneficiary value.
     *
     * @return the beneficiary value
     */
    public AadIdentifier beneficiary() {
        return this.beneficiary;
    }

    /**
     * Set the beneficiary value.
     *
     * @param beneficiary the beneficiary value to set
     * @return the Subscription object itself.
     */
    public Subscription withBeneficiary(AadIdentifier beneficiary) {
        this.beneficiary = beneficiary;
        return this;
    }

    /**
     * Get the purchaser value.
     *
     * @return the purchaser value
     */
    public AadIdentifier purchaser() {
        return this.purchaser;
    }

    /**
     * Set the purchaser value.
     *
     * @param purchaser the purchaser value to set
     * @return the Subscription object itself.
     */
    public Subscription withPurchaser(AadIdentifier purchaser) {
        this.purchaser = purchaser;
        return this;
    }

    /**
     * Get the planId value.
     *
     * @return the planId value
     */
    public String planId() {
        return this.planId;
    }

    /**
     * Set the planId value.
     *
     * @param planId the planId value to set
     * @return the Subscription object itself.
     */
    public Subscription withPlanId(String planId) {
        this.planId = planId;
        return this;
    }

    /**
     * Get the quantity value.
     *
     * @return the quantity value
     */
    public Integer quantity() {
        return this.quantity;
    }

    /**
     * Set the quantity value.
     *
     * @param quantity the quantity value to set
     * @return the Subscription object itself.
     */
    public Subscription withQuantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Get the term value.
     *
     * @return the term value
     */
    public SubscriptionTerm term() {
        return this.term;
    }

    /**
     * Set the term value.
     *
     * @param term the term value to set
     * @return the Subscription object itself.
     */
    public Subscription withTerm(SubscriptionTerm term) {
        this.term = term;
        return this;
    }

    /**
     * Get indicating whether the current subscription is a test asset.
     *
     * @return the isTest value
     */
    public Boolean isTest() {
        return this.isTest;
    }

    /**
     * Set indicating whether the current subscription is a test asset.
     *
     * @param isTest the isTest value to set
     * @return the Subscription object itself.
     */
    public Subscription withIsTest(Boolean isTest) {
        this.isTest = isTest;
        return this;
    }

    /**
     * Get true - the customer subscription is currently in free trial, false - the customer subscription is not currently in free trial.(optional field - default false).
     *
     * @return the isFreeTrial value
     */
    public Boolean isFreeTrial() {
        return this.isFreeTrial;
    }

    /**
     * Set true - the customer subscription is currently in free trial, false - the customer subscription is not currently in free trial.(optional field - default false).
     *
     * @param isFreeTrial the isFreeTrial value to set
     * @return the Subscription object itself.
     */
    public Subscription withIsFreeTrial(Boolean isFreeTrial) {
        this.isFreeTrial = isFreeTrial;
        return this;
    }

    /**
     * Get the allowedCustomerOperations value.
     *
     * @return the allowedCustomerOperations value
     */
    public List<AllowedCustomerOperationsEnum> allowedCustomerOperations() {
        return this.allowedCustomerOperations;
    }

    /**
     * Set the allowedCustomerOperations value.
     *
     * @param allowedCustomerOperations the allowedCustomerOperations value to set
     * @return the Subscription object itself.
     */
    public Subscription withAllowedCustomerOperations(List<AllowedCustomerOperationsEnum> allowedCustomerOperations) {
        this.allowedCustomerOperations = allowedCustomerOperations;
        return this;
    }

    /**
     * Get the sessionId value.
     *
     * @return the sessionId value
     */
    public UUID sessionId() {
        return this.sessionId;
    }

    /**
     * Set the sessionId value.
     *
     * @param sessionId the sessionId value to set
     * @return the Subscription object itself.
     */
    public Subscription withSessionId(UUID sessionId) {
        this.sessionId = sessionId;
        return this;
    }

    /**
     * Get the fulfillmentId value.
     *
     * @return the fulfillmentId value
     */
    public UUID fulfillmentId() {
        return this.fulfillmentId;
    }

    /**
     * Set the fulfillmentId value.
     *
     * @param fulfillmentId the fulfillmentId value to set
     * @return the Subscription object itself.
     */
    public Subscription withFulfillmentId(UUID fulfillmentId) {
        this.fulfillmentId = fulfillmentId;
        return this;
    }

    /**
     * Get the storeFront value.
     *
     * @return the storeFront value
     */
    public String storeFront() {
        return this.storeFront;
    }

    /**
     * Set the storeFront value.
     *
     * @param storeFront the storeFront value to set
     * @return the Subscription object itself.
     */
    public Subscription withStoreFront(String storeFront) {
        this.storeFront = storeFront;
        return this;
    }

    /**
     * Get dry Run indicates all transactions run as Test-Mode in the commerce stack. Possible values include: 'None', 'DryRun'.
     *
     * @return the sessionMode value
     */
    public SessionModeEnum sessionMode() {
        return this.sessionMode;
    }

    /**
     * Set dry Run indicates all transactions run as Test-Mode in the commerce stack. Possible values include: 'None', 'DryRun'.
     *
     * @param sessionMode the sessionMode value to set
     * @return the Subscription object itself.
     */
    public Subscription withSessionMode(SessionModeEnum sessionMode) {
        this.sessionMode = sessionMode;
        return this;
    }

    /**
     * Get possible Values are None, Csp (Csp sandbox purchase). Possible values include: 'None', 'Csp'.
     *
     * @return the sandboxType value
     */
    public SandboxTypeEnum sandboxType() {
        return this.sandboxType;
    }

    /**
     * Set possible Values are None, Csp (Csp sandbox purchase). Possible values include: 'None', 'Csp'.
     *
     * @param sandboxType the sandboxType value to set
     * @return the Subscription object itself.
     */
    public Subscription withSandboxType(SandboxTypeEnum sandboxType) {
        this.sandboxType = sandboxType;
        return this;
    }

}
