/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SubscriptionTerm model.
 */
public class SubscriptionTerm {
    /**
     * The startDate property.
     */
    @JsonProperty(value = "startDate")
    private DateTime startDate;

    /**
     * The endDate property.
     */
    @JsonProperty(value = "endDate")
    private DateTime endDate;

    /**
     * Get the startDate value.
     *
     * @return the startDate value
     */
    public DateTime startDate() {
        return this.startDate;
    }

    /**
     * Set the startDate value.
     *
     * @param startDate the startDate value to set
     * @return the SubscriptionTerm object itself.
     */
    public SubscriptionTerm withStartDate(DateTime startDate) {
        this.startDate = startDate;
        return this;
    }

    /**
     * Get the endDate value.
     *
     * @return the endDate value
     */
    public DateTime endDate() {
        return this.endDate;
    }

    /**
     * Set the endDate value.
     *
     * @param endDate the endDate value to set
     * @return the SubscriptionTerm object itself.
     */
    public SubscriptionTerm withEndDate(DateTime endDate) {
        this.endDate = endDate;
        return this;
    }

}
