/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.azure.marketplace.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The UpdateOperation model.
 */
public class UpdateOperation {
    /**
     * The planId property.
     */
    @JsonProperty(value = "planId")
    private String planId;

    /**
     * The quantity property.
     */
    @JsonProperty(value = "quantity")
    private Long quantity;

    /**
     * Possible values include: 'Success', 'Failure'.
     */
    @JsonProperty(value = "status")
    private UpdateOperationStatusEnum status;

    /**
     * Get the planId value.
     *
     * @return the planId value
     */
    public String planId() {
        return this.planId;
    }

    /**
     * Set the planId value.
     *
     * @param planId the planId value to set
     * @return the UpdateOperation object itself.
     */
    public UpdateOperation withPlanId(String planId) {
        this.planId = planId;
        return this;
    }

    /**
     * Get the quantity value.
     *
     * @return the quantity value
     */
    public Long quantity() {
        return this.quantity;
    }

    /**
     * Set the quantity value.
     *
     * @param quantity the quantity value to set
     * @return the UpdateOperation object itself.
     */
    public UpdateOperation withQuantity(Long quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Get possible values include: 'Success', 'Failure'.
     *
     * @return the status value
     */
    public UpdateOperationStatusEnum status() {
        return this.status;
    }

    /**
     * Set possible values include: 'Success', 'Failure'.
     *
     * @param status the status value to set
     * @return the UpdateOperation object itself.
     */
    public UpdateOperation withStatus(UpdateOperationStatusEnum status) {
        this.status = status;
        return this;
    }

}
